export function getApplicationElements(document) {
  return {
    form: document.getElementById('qr-form'),
    canvas: document.getElementById('qr-canvas'),
    qrViewport: document.getElementById('qr-preview-viewport'),
    viewControls: document.getElementById('preview-view-controls'),
    previewViewFit: document.getElementById('preview-view-fit'),
    actualView: document.getElementById('preview-view-actual'),
    chunkPreviewNav: document.getElementById('chunk-preview-nav'),
    chunkPreviewPrev: document.getElementById('chunk-preview-prev'),
    chunkPreviewNext: document.getElementById('chunk-preview-next'),
    chunkStatus: document.getElementById('chunk-preview-status'),
    encodedPreview: document.getElementById('encoded-preview'),
    qrFormat: document.getElementById('qr-format'),
    bulkEnabled: document.getElementById('bulk-enabled'),
    qrVersion: document.getElementById('qr-version'),
    qrVersionValue: document.getElementById('qr-version-value'),
    versionAuto: document.getElementById('version-auto'),
    maskPattern: document.getElementById('mask-pattern'),
    qrWidth: document.getElementById('qr-width'),
    qrWidthAuto: document.getElementById('qr-width-auto'),
    qrScale: document.getElementById('qr-scale'),
    qrMargin: document.getElementById('qr-margin'),
    errorCorrection: document.getElementById('error-correction'),
    ecLabel: document.getElementById('error-correction-label'),
    ecHelp: document.getElementById('error-correction-help'),
    modeAuto: document.getElementById('mode-auto'),
    encodingMode: document.getElementById('encoding-mode'),
    modeButtons: document.querySelectorAll('.encoding-mode-button'),
    formatValidation: document.getElementById('format-validation'),
    tabButtons: document.querySelectorAll('.tab-button'),
    tabPanels: document.querySelectorAll('.tab-panel'),
    subtabButtons: document.querySelectorAll('.content-subtab-button'),
    subtabPanels: document.querySelectorAll('.content-subtab-panel'),
    urlInput: document.getElementById('url-input'),
  };
}
