const COPY = {
  'en-US': {
    title: 'QR Code Generator Handbook',
    contents: 'Contents',
    download: 'Download handbook',
    choose: 'Choose a download format.',
    pdf: 'PDF',
    print: 'Print / save PDF',
    epub: 'Download ePub',
    preparing: 'Preparing handbook...',
    blocked: 'The print window was blocked.',
    failed: 'The handbook could not be created.',
    cancel: 'Cancel',
    creatingPdf: 'Creating PDF handbook...',
    creatingEpub: 'Creating EPUB handbook...',
  },
  'en-GB': {
    title: 'QR Code Generator Handbook',
    contents: 'Contents',
    download: 'Download handbook',
    choose: 'Choose a download format.',
    pdf: 'PDF',
    print: 'Print / save PDF',
    epub: 'Download ePub',
    preparing: 'Preparing handbook...',
    blocked: 'The print window was blocked.',
    failed: 'The handbook could not be created.',
    cancel: 'Cancel',
    creatingPdf: 'Creating PDF handbook...',
    creatingEpub: 'Creating EPUB handbook...',
  },
  es: {
    title: 'Manual del generador de códigos QR',
    contents: 'Índice',
    download: 'Descargar el manual',
    choose: 'Elija un formato de descarga.',
    pdf: 'PDF',
    print: 'Imprimir / guardar PDF',
    epub: 'Descargar ePub',
    preparing: 'Preparando el manual...',
    blocked: 'El navegador bloqueó la ventana de impresión.',
    failed: 'No se pudo crear el manual.',
    cancel: 'Cancelar',
    creatingPdf: 'Creando el manual en PDF...',
    creatingEpub: 'Creando el manual en EPUB...',
  },
  ar: {
    title: 'دليل مولّد رموز QR',
    contents: 'المحتويات',
    download: 'تنزيل الدليل',
    choose: 'اختر تنسيق التنزيل.',
    pdf: 'PDF',
    print: 'طباعة / حفظ PDF',
    epub: 'تنزيل ePub',
    preparing: 'جارٍ إعداد الدليل...',
    blocked: 'حظر المتصفح نافذة الطباعة.',
    failed: 'تعذّر إنشاء الدليل.',
    cancel: 'إلغاء',
    creatingPdf: 'جارٍ إنشاء دليل PDF...',
    creatingEpub: 'جارٍ إنشاء دليل EPUB...',
  },
  'hi-IN': {
    title: 'QR कोड जेनरेटर पुस्तिका',
    contents: 'विषय-सूची',
    download: 'पुस्तिका डाउनलोड करें',
    choose: 'डाउनलोड प्रारूप चुनें।',
    pdf: 'PDF',
    print: 'प्रिंट करें / PDF सहेजें',
    epub: 'ePub डाउनलोड करें',
    preparing: 'पुस्तिका तैयार की जा रही है...',
    blocked: 'ब्राउज़र ने प्रिंट विंडो को ब्लॉक कर दिया।',
    failed: 'पुस्तिका नहीं बनाई जा सकी।',
    cancel: 'रद्द करें',
    creatingPdf: 'PDF पुस्तिका बनाई जा रही है...',
    creatingEpub: 'EPUB पुस्तिका बनाई जा रही है...',
  },
  'zh-CN': {
    title: '二维码生成器手册',
    contents: '目录',
    download: '下载手册',
    choose: '请选择下载格式。',
    pdf: 'PDF',
    print: '打印 / 保存 PDF',
    epub: '下载 ePub',
    preparing: '正在准备手册...',
    blocked: '浏览器阻止了打印窗口。',
    failed: '无法创建手册。',
    cancel: '取消',
    creatingPdf: '正在创建 PDF 手册...',
    creatingEpub: '正在创建 EPUB 手册...',
  },
};

export function getHandbookCopy(locale) {
  return COPY[locale] || COPY['en-US'];
}
