export function getStyleElements(document) {
  const id = (name) => document.getElementById(name);
  return {
    colorDark: id('color-dark'),
    colorLight: id('color-light'),
    colorDarkTransparency: id('color-dark-transparency'),
    colorDarkTransparencyValue: id('color-dark-transparency-value'),
    colorLightTransparency: id('color-light-transparency'),
    colorLightTransparencyValue: id('color-light-transparency-value'),
    gradientType: id('gradient-type'),
    gradientControls: id('gradient-controls'),
    gradientAngleControls: id('gradient-angle-controls'),
    gradientAngle: id('gradient-angle'),
    gradientAngleValue: id('gradient-angle-value'),
    colorGradientEnd: id('color-gradient-end'),
    colorGradientEndTransparency: id('color-gradient-end-transparency'),
    colorGradientEndTransparencyValue: id(
      'color-gradient-end-transparency-value',
    ),
    imageFillControls: id('image-fill-controls'),
    imageFillInput: id('image-fill-input'),
    imageFillRecommended: id('image-fill-recommended'),
    imageFillClear: id('image-fill-clear'),
    moduleShape: id('module-shape'),
    moduleCustomControls: id('module-custom-controls'),
    moduleRounding: id('module-rounding'),
    moduleRoundingValue: id('module-rounding-value'),
    moduleInset: id('module-inset'),
    moduleInsetValue: id('module-inset-value'),
    moduleRotation: id('module-rotation'),
    moduleRotationValue: id('module-rotation-value'),
    eyeShape: id('eye-shape'),
    eyeCustomControls: id('eye-custom-controls'),
    eyeOuterRounding: id('eye-outer-rounding'),
    eyeOuterRoundingValue: id('eye-outer-rounding-value'),
    eyeCenterRounding: id('eye-center-rounding'),
    eyeCenterRoundingValue: id('eye-center-rounding-value'),
    eyeCustomColorsEnabled: id('eye-custom-colors-enabled'),
    eyeColorControls: id('eye-color-controls'),
    eyeOuterColor: id('eye-outer-color'),
    eyeCenterColor: id('eye-center-color'),
    centerArtMode: id('center-art-mode'),
    centerArtControls: id('center-art-controls'),
    centerArtSize: id('center-art-size'),
    centerArtSizeValue: id('center-art-size-value'),
    centerArtBackground: id('center-art-background'),
    centerArtBackgroundLabel: id('center-art-background-label'),
    centerLogoControls: id('center-logo-controls'),
    centerLogoInput: id('center-logo-input'),
    centerLogoClear: id('center-logo-clear'),
    centerEmojiControls: id('center-emoji-controls'),
    centerEmoji: id('center-emoji'),
    emojiOptions: document.querySelectorAll('.emoji-option'),
    centerPixelControls: id('center-pixel-controls'),
    pixelArtColor: id('pixel-art-color'),
    pixelArtClear: id('pixel-art-clear'),
    pixelArtPalette: id('pixel-art-palette'),
    pixelArtMatchModuleShape: id('pixel-art-match-module-shape'),
    pixelArtSizeInput: id('pixel-art-size'),
    pixelArtSizeValue: id('pixel-art-size-value'),
    pixelArtGrid: id('pixel-art-grid'),
  };
}
